#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script: step14_regenerate_arc_figures.py | Topic: 10
Purpose: Generate manuscript figures for the ARC consequence analysis so that
         figures match the ARC nested-logistic-regression definitions.
         Deterministic: same seed-42 70/30 split and pipeline as step13 / step_v5.

Produces (PNG + vector PDF):
  Fig1  fig1_consort_arc           CONSORT incl. data-quality audit -> ARC n=528
  Fig4  fig4_subgroup_forest_arc   M1 AUROC subgroup forest, ARC test n=159
  S1    suppfig1_threshold_arc     M1 threshold sensitivity (ARC, clean labels)
  S3    suppfig3_ladder_arc        AUROC ladder M0->M4 (ARC test n=159)
  S4    suppfig4_dca_arc           DCA M0-M4 (ARC test n=159)
  S5    suppfig5_shap_arc          SHAP for M3 logistic (full ARC)
  S6    suppfig6_ritertile_arc     M1/M3 AUROC by RI tertile (ARC test)

Fig2 (fig2_map_distribution) and Fig3 (fig3_arc_nested_roc) are generated by
step_v5_analyses.py and step13_fig3_arc_nested_roc.py respectively.
"""
import warnings; warnings.filterwarnings('ignore')
import json
import numpy as np, pandas as pd
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, roc_curve

np.random.seed(42)
PROC = (Path(__file__).resolve().parents[1] / "data/processed")
FIG  = (Path(__file__).resolve().parents[1] / "outputs/figures")
MET  = (Path(__file__).resolve().parents[1] / "outputs/metrics")

plt.rcParams.update({'font.size':9,'axes.spines.top':False,'axes.spines.right':False,
                     'figure.dpi':300,'savefig.dpi':300})

def save(fig, stem):
    fig.savefig(FIG / f"{stem}.png", dpi=300, bbox_inches='tight')
    fig.savefig(FIG / f"{stem}.pdf", format='pdf', bbox_inches='tight')
    plt.close(fig)
    print(f"  saved {stem}.png + .pdf")

# ── Load + ARC definition (identical to step13 / step_v5) ──────────────────────
feat = pd.read_parquet(PROC / "vascular_features.parquet")
outcome = pd.read_parquet(PROC / "outcome_labels.parquet")
feat = feat.merge(outcome[['caseid', 'crash_absolute']], on='caseid', how='left')
arc = feat[feat['drop_pct'].notna() & np.isfinite(feat['drop_pct']) & (feat['drop_pct'] > -500)].copy()

CLIN = ['age', 'bmi', 'asa', 'preop_htn', 'preop_dm']
y_all = arc['crash_30'].values
tr_idx, te_idx = train_test_split(arc.index.values, test_size=0.30,
                                  stratify=y_all, random_state=42)
tr, te = arc.loc[tr_idx], arc.loc[te_idx]
y_tr, y_te = tr['crash_30'].values, te['crash_30'].values
print(f"ARC N={len(arc)} events={int(y_all.sum())} | Train={len(tr)} Test={len(te)} (events={int(y_te.sum())})")

def pipe():
    return Pipeline([('imp', SimpleImputer(strategy='median')),
                     ('sc', StandardScaler()),
                     ('lr', LogisticRegression(max_iter=1000, random_state=42))])

MODELS = {
    'M0': CLIN,
    'M1': CLIN + ['baseline_map'],
    'M2': CLIN + ['ri_mean_clean'],
    'M3': CLIN + ['baseline_map', 'ri_mean_clean'],
    'M4': CLIN + ['baseline_map', 'ri_mean_clean', 'ppg_amp_clean'],
}
# fit all, keep test probabilities
proba_te, auc_te = {}, {}
for m, fs in MODELS.items():
    p = pipe(); p.fit(tr[fs].values, y_tr)
    proba_te[m] = p.predict_proba(te[fs].values)[:, 1]
    auc_te[m] = roc_auc_score(y_te, proba_te[m])
print("  ARC test AUROC:", {m: round(a, 3) for m, a in auc_te.items()})

def boot_ci(yt, ys, n=1000, seed=0):
    r = np.random.default_rng(seed); a = []
    yt = np.asarray(yt); ys = np.asarray(ys)
    for _ in range(n):
        idx = r.choice(len(yt), len(yt), replace=True)
        if len(np.unique(yt[idx])) < 2: continue
        a.append(roc_auc_score(yt[idx], ys[idx]))
    return (np.percentile(a, 2.5), np.percentile(a, 97.5)) if a else (np.nan, np.nan)

COL = {'M0':'#888888','M1':'#4C9BD5','M2':'#E8A33D','M3':'#2E8B72','M4':'#C8502A'}

# ═══════════════════════ FIG 1 : CONSORT incl. ARC branch ═════════════════════
print("\n[Fig1] CONSORT with data-quality audit / ARC branch")
flow = json.load(open(MET / "cohort_flowchart_numbers.json"))
n_undef, n_inf, n_extreme = 231, 86, 64           # invalid DeltaMAP% label breakdown
n_excl_dq = n_undef + n_inf + n_extreme           # 381
n_final909 = 909
n_arc = len(arc)                                  # 528
n_arc_event = int(y_all.sum())                    # 142
n_arc_noevent = n_arc - n_arc_event               # 386
assert n_final909 - n_excl_dq == n_arc, (n_final909, n_excl_dq, n_arc)

fig, ax = plt.subplots(figsize=(6.6, 9.2)); ax.set_xlim(0, 10); ax.set_ylim(0, 12.4); ax.axis('off')
CX, EX, BW, BWE, BH = 5.0, 8.6, 4.2, 3.4, 0.74
def box(x, y, t, c='#E8F4FD', fs=7.5, bold=False):
    ax.add_patch(mpatches.FancyBboxPatch((x-BW/2, y-BH/2), BW, BH, boxstyle="round,pad=0.02",
                 facecolor=c, edgecolor='#333', lw=0.8, zorder=2))
    ax.text(x, y, t, ha='center', va='center', fontsize=fs, fontweight='bold' if bold else 'normal', zorder=3)
def ebox(x, y, t):
    ax.add_patch(mpatches.FancyBboxPatch((x-BWE/2, y-BH/2), BWE, BH, boxstyle="round,pad=0.02",
                 facecolor='#FFF3CD', edgecolor='#CC8800', lw=0.8, zorder=2))
    ax.text(x, y, t, ha='center', va='center', fontsize=6.6, color='#5C4A00', zorder=3)
def arr(y1, y2, x=CX):
    ax.annotate('', xy=(x, y2), xytext=(x, y1), arrowprops=dict(arrowstyle='->', color='#555', lw=0.8), zorder=1)
def sidearr(y): ax.annotate('', xy=(EX-BWE/2, y), xytext=(CX+BW/2, y), arrowprops=dict(arrowstyle='->', color='#999', lw=0.7), zorder=1)

ys = [11.6, 10.3, 9.0, 7.7, 6.4, 5.1]
box(CX, ys[0], f"VitalDB TIVA cases screened\nN = {flow['total']:,}", c='#D6EAD6', bold=True)
box(CX, ys[1], f"Adults (age $\\geq$ 18 y)\nN = {flow['age_18_plus']:,}")
ebox(EX, ys[1], f"Excluded age < 18:\nN = {flow['total']-flow['age_18_plus']}")
box(CX, ys[2], f"General anaesthesia\nN = {flow['general_anesthesia']:,}")
ebox(EX, ys[2], f"Excluded non-general:\nN = {flow['age_18_plus']-flow['general_anesthesia']}")
box(CX, ys[3], f"Non-cardiac / non-thoracic\nN = {flow['exclude_cardiac']:,}")
ebox(EX, ys[3], f"Excluded cardiac/thoracic:\nN = {flow['general_anesthesia']-flow['exclude_cardiac']}")
box(CX, ys[4], f"Required tracks (ABP+PPG+Propofol)\nN = {flow['has_required_tracks']:,}")
ebox(EX, ys[4], f"Missing required tracks:\nN = {flow['exclude_cardiac']-flow['has_required_tracks']:,}")
box(CX, ys[5], f"Met inclusion criteria\nN = {n_final909:,}", c='#E8F4FD', bold=True)
ebox(EX, ys[5], f"Outcome/label incomplete:\nN = {flow['has_required_tracks']-n_final909}")
for a, b in zip(ys[:-1], ys[1:]): arr(a-BH/2, b+BH/2)
for yy in ys[1:]: sidearr(yy)

# data-quality audit step
y_dq = 3.7
box(CX, y_dq, f"Data-quality audit:\nartefact-reduced cohort (ARC)\nN = {n_arc}  ($n_{{events}}$ = {n_arc_event})", c='#FCE8D6', fs=7.3, bold=True)
ebox(EX, y_dq, f"Invalid $\\Delta$MAP% labels: N = {n_excl_dq}\n  undefined {n_undef}; infinite {n_inf};\n  extreme-negative {n_extreme}")
arr(ys[5]-BH/2, y_dq+BH/2); sidearr(y_dq)
# ARC outcome split
y_out = 1.9
ax.add_patch(mpatches.FancyBboxPatch((3.05-1.7, y_out-BH/2), 3.4, BH, boxstyle="round,pad=0.02", facecolor='#F8D7DA', edgecolor='#A33', lw=0.8, zorder=2))
ax.text(3.05, y_out, f"Induction MAP-decrease\nevent: N = {n_arc_event} ({n_arc_event/n_arc*100:.1f}%)", ha='center', va='center', fontsize=6.9, zorder=3)
ax.add_patch(mpatches.FancyBboxPatch((6.95-1.7, y_out-BH/2), 3.4, BH, boxstyle="round,pad=0.02", facecolor='#D1ECF1', edgecolor='#268', lw=0.8, zorder=2))
ax.text(6.95, y_out, f"No event: N = {n_arc_noevent} ({n_arc_noevent/n_arc*100:.1f}%)", ha='center', va='center', fontsize=6.9, zorder=3)
ax.annotate('', xy=(3.05, y_out+BH/2), xytext=(CX, y_dq-BH/2), arrowprops=dict(arrowstyle='->', color='#555', lw=0.8))
ax.annotate('', xy=(6.95, y_out+BH/2), xytext=(CX, y_dq-BH/2), arrowprops=dict(arrowstyle='->', color='#555', lw=0.8))
ax.set_title("Figure 1. Study flow diagram (CONSORT-style)", fontsize=9, fontweight='bold', pad=6)
save(fig, "fig1_consort_arc")

# ═══════════════════════ FIG 4 : M1 subgroup forest (ARC test) ════════════════
print("\n[Fig4] M1 subgroup forest (ARC test n=159)")
te2 = te.copy(); te2['_p'] = proba_te['M1']; te2['_y'] = y_te
subs = [('Overall', np.ones(len(te2), bool))]
subs += [('Age < 65', te2['age'] < 65), ('Age $\\geq$ 65', te2['age'] >= 65)]
subs += [('Male', te2['sex'] == 'M'), ('Female', te2['sex'] == 'F')]
subs += [('BMI < 25', te2['bmi'] < 25), ('BMI $\\geq$ 25', te2['bmi'] >= 25)]
subs += [('ASA I-II', te2['asa'] <= 2), ('ASA III-IV', te2['asa'] >= 3)]
subs += [('Hypertension', te2['preop_htn'] == 1), ('No hypertension', te2['preop_htn'] == 0)]
subs += [('Diabetes', te2['preop_dm'] == 1), ('No diabetes', te2['preop_dm'] == 0)]
rows = []
for name, mask in subs:
    m = mask.values if hasattr(mask, 'values') else mask
    yy = te2['_y'].values[m]; pp = te2['_p'].values[m]
    n = int(m.sum()); ev = int(yy.sum())
    if len(np.unique(yy)) < 2 or ev < 3 or (n - ev) < 3:
        rows.append((name, np.nan, np.nan, np.nan, n, ev)); continue
    a = roc_auc_score(yy, pp); lo, hi = boot_ci(yy, pp, seed=1)
    rows.append((name, a, lo, hi, n, ev))
fig, ax = plt.subplots(figsize=(6.4, 6.6))
yp = np.arange(len(rows))[::-1]
ov = rows[0][1]
ax.axvline(ov, color='#C8502A', ls='--', lw=1, alpha=0.8)
for yi, (name, a, lo, hi, n, ev) in zip(yp, rows):
    if np.isnan(a):
        ax.text(0.515, yi, f"{name}  (n={n}, ev={ev}: too few)", va='center', fontsize=7.5, color='#999'); continue
    c = '#C8502A' if name == 'Overall' else '#1f6fb2'
    mk = 'D' if name == 'Overall' else 'o'
    ax.plot([lo, hi], [yi, yi], color=c, lw=1.6)
    ax.plot(a, yi, mk, color=c, ms=7 if name == 'Overall' else 5)
    ax.text(1.015, yi, f"{a:.3f} [{lo:.3f}–{hi:.3f}]  n={n}", va='center', fontsize=7.3)
ax.set_yticks(yp); ax.set_yticklabels([r[0] for r in rows], fontsize=8.5)
ax.set_xlim(0.5, 1.0); ax.set_xlabel('M1 AUROC (95% CI)')
ax.set_title('Subgroup analysis — M1 (clinical + MAP), ARC test set ($n$=159)\n'
             'Exploratory; subgroup cells are small', fontsize=9, fontweight='bold')
save(fig, "fig4_subgroup_forest_arc")

# ═══════════════════════ SUPP FIG 1 : threshold sensitivity (ARC) ═════════════
print("\n[SuppFig1] threshold sensitivity (ARC clean labels)")
ts = pd.read_csv(MET / "threshold_sensitivity_clean.csv")
fig, ax = plt.subplots(figsize=(6.2, 4.2))
ax.errorbar(ts['threshold'], ts['auroc'],
            yerr=[ts['auroc']-ts['auroc_lo'], ts['auroc_hi']-ts['auroc']],
            fmt='o-', color='#1f6fb2', lw=2, ms=7, capsize=4)
ax.axhline(0.7, color='#999', ls='--', lw=1, label='AUROC = 0.70')
ax.set_xlabel('MAP-decrease threshold (%)'); ax.set_ylabel('M1 AUROC (95% CI)')
ax.set_ylim(0.5, 1.0)
ax.set_title('M1 performance across MAP-decrease definitions (ARC test set)', fontsize=9, fontweight='bold')
ax.legend(fontsize=8, loc='lower left')
save(fig, "suppfig1_threshold_arc")

# ═══════════════════════ SUPP FIG 3 : AUROC ladder (ARC) ══════════════════════
print("\n[SuppFig3] AUROC ladder (ARC test n=159)")
order = ['M0', 'M1', 'M2', 'M3', 'M4']
labels = {'M0':'M0: Clinical only','M1':'M1: + Baseline MAP','M2':'M2: + RI only',
          'M3':'M3: + MAP + RI','M4':'M4: + MAP + RI + Amp'}
cis = {m: boot_ci(y_te, proba_te[m], seed=2) for m in order}
fig, ax = plt.subplots(figsize=(6.4, 4.4))
yp = np.arange(len(order))
for i, m in enumerate(order):
    a = auc_te[m]; lo, hi = cis[m]
    ax.barh(i, a, color=COL[m], edgecolor='white', height=0.62, zorder=2)
    ax.plot([lo, hi], [i, i], color='#333', lw=1.4, zorder=3)
    ax.text(a+0.006, i, f"{a:.3f}", va='center', fontsize=8.5, zorder=4)
ax.axvline(0.5, color='#999', ls='--', lw=1)
d10 = auc_te['M1']-auc_te['M0']; d31 = auc_te['M3']-auc_te['M1']
ax.set_yticks(yp); ax.set_yticklabels([labels[m] for m in order], fontsize=8.5)
ax.set_xlim(0.45, 1.0); ax.set_xlabel('AUROC (ARC held-out test set, $n$=159)')
ax.set_title(f'Incremental AUROC ladder — ARC\n'
             f'$\\Delta$(M1$-$M0)=+{d10:.3f};  $\\Delta$(M3$-$M1)={d31:+.3f}',
             fontsize=9, fontweight='bold')
save(fig, "suppfig3_ladder_arc")

# ═══════════════════════ SUPP FIG 4 : DCA M0-M4 (ARC test) ════════════════════
print("\n[SuppFig4] Decision curve analysis (ARC test n=159)")
def net_benefit(y_true, p, pt):
    y_true = np.asarray(y_true); n = len(y_true)
    pred = p >= pt
    tp = np.sum(pred & (y_true == 1)); fp = np.sum(pred & (y_true == 0))
    return tp/n - fp/n * (pt/(1-pt))
pts = np.linspace(0.01, 0.70, 70)
prev = y_te.mean()
fig, ax = plt.subplots(figsize=(6.3, 4.6))
ax.plot(pts, [prev - (1-prev)*(t/(1-t)) for t in pts], color='#bbb', ls=':', lw=1.2, label='Treat all')
ax.axhline(0, color='#333', ls='--', lw=1, label='Treat none')
for m in ['M0', 'M1', 'M3', 'M4']:
    nb = [net_benefit(y_te, proba_te[m], t) for t in pts]
    ax.plot(pts, nb, color=COL[m], lw=2 if m in ('M1','M3') else 1.4, label=f'{m} ({labels[m].split(": ")[1]})')
ax.set_xlabel('Threshold probability'); ax.set_ylabel('Net benefit')
ax.set_ylim(-0.05, max(prev+0.02, 0.3)); ax.set_xlim(0, 0.7)
ax.set_title('Decision curve analysis — nested models, ARC test set ($n$=159)', fontsize=9, fontweight='bold')
ax.legend(fontsize=7.2, loc='upper right')
save(fig, "suppfig4_dca_arc")

# ═══════════════════════ SUPP FIG 5 : SHAP for M3 logistic (full ARC) ═════════
print("\n[SuppFig5] SHAP for M3 logistic regression (full ARC)")
import shap
M3_FEATS = CLIN + ['baseline_map', 'ri_mean_clean']
NAMES = ['Age', 'BMI', 'ASA physical status', 'Pre-op hypertension',
         'Pre-op diabetes', 'Baseline MAP (mmHg)', 'Reflection index (PPG)']
Xfull = arc[M3_FEATS].values
yfull = arc['crash_30'].values
imp = SimpleImputer(strategy='median'); sc = StandardScaler()
Xt = sc.fit_transform(imp.fit_transform(Xfull))
lr = LogisticRegression(max_iter=1000, random_state=42).fit(Xt, yfull)
expl = shap.LinearExplainer(lr, Xt)
sv = expl.shap_values(Xt)
fig = plt.figure(figsize=(6.4, 4.2))
shap.summary_plot(sv, features=Xt, feature_names=NAMES, show=False, plot_size=None, sort=True)
fig = plt.gcf(); fig.set_size_inches(6.4, 4.2)
plt.title('SHAP summary — M3 (clinical + MAP + RI), logistic regression, full ARC',
          fontsize=8.5, fontweight='bold')
plt.xlabel('SHAP value (impact on log-odds of induction MAP-decrease)', fontsize=8)
save(fig, "suppfig5_shap_arc")

# ═══════════════════════ SUPP FIG 6 : M1/M3 AUROC by RI tertile (ARC test) ════
print("\n[SuppFig6] M1 & M3 AUROC by RI tertile (ARC test)")
ri_te = te['ri_mean_clean'].values
# tertile edges from full ARC RI (clean), applied to test
edges = np.nanpercentile(arc['ri_mean_clean'].dropna().values, [33.333, 66.667])
def tert(v):
    if np.isnan(v): return -1
    return 0 if v <= edges[0] else (1 if v <= edges[1] else 2)
tlab = ['T1 (low RI)', 'T2 (mid RI)', 'T3 (high RI)']
groups = {}
for ti in range(3):
    mask = np.array([tert(v) == ti for v in ri_te])
    groups[ti] = mask
fig, ax = plt.subplots(figsize=(6.2, 4.3))
width = 0.36
xs = np.arange(3)
for j, m in enumerate(['M1', 'M3']):
    vals, los, his, ns = [], [], [], []
    for ti in range(3):
        mask = groups[ti]; yy = y_te[mask]; pp = proba_te[m][mask]
        ns.append(int(mask.sum()))
        if len(np.unique(yy)) < 2 or yy.sum() < 3 or (len(yy)-yy.sum()) < 3:
            vals.append(np.nan); los.append(np.nan); his.append(np.nan); continue
        a = roc_auc_score(yy, pp); lo, hi = boot_ci(yy, pp, seed=3)
        vals.append(a); los.append(a-lo); his.append(hi-a)
    off = (j-0.5)*width
    ax.bar(xs+off, vals, width, color=COL[m], label=m, edgecolor='white',
           yerr=[np.nan_to_num(los), np.nan_to_num(his)], capsize=3)
ax.set_xticks(xs); ax.set_xticklabels([f"{tlab[i]}\n(n={int(groups[i].sum())})" for i in range(3)], fontsize=8)
ax.set_ylabel('AUROC (ARC test set)'); ax.set_ylim(0, 1.05)
ax.axhline(0.5, color='#999', ls='--', lw=0.8)
ax.set_title('M1 vs M3 AUROC stratified by reflection-index tertile (ARC test)\n'
             'RI adds no discrimination within any tertile', fontsize=9, fontweight='bold')
ax.legend(fontsize=8, loc='lower right')
save(fig, "suppfig6_ritertile_arc")

print("\n=== ALL ARC FIGURES REGENERATED ===")
